#Segmentación de clientes para personalización de campañas de marketing.

##Proceso de Recolección de datos

**1. Fuentes:**

* Identificación de las fuentes

   - Fichero CSV bank_dataset.csv

* Descripcion de las fuentes

   - El conjunto de datos en el fichero contiene 11163 registros, y 17 entradas, estan separados por coma y contienen como primera fila header.

**2. Métodos de recoleecion de datos:**

* Procedimiento y herramientas:
  - Lectura del fichero CSV, almacenado en google drive, leido desde google colab con la libreria pandas de python mediante read_csv.

* Frecuencia de recolección:
  - Puntual.

* Script de Descarga


```
import pandas as pd
bank = pd.read_csv('/content/drive/MyDrive/bank_dataset.csv')
print(bank)
```

In [6]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

bank = pd.read_csv('/content/drive/MyDrive/bank_dataset.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
bank

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59.0,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56.0,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41.0,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55.0,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54.0,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33.0,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39.0,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32.0,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43.0,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34.0,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no


**3. Formato y Estructura de los datos**

* Tipo de datos:
   - Numericos: Age, balance, day, duration, campaign, pdays, previous
   - Categoricos: job, marital, education, poutcome, housing, month
   - Binario: default, alojamiento, loan, y deposit

* Formato de Almacenamiento:
   - Datos tabulares en fichero csv

**4. Limitaciones de los datos**

* Son descargados de manera puntual y puede existir la posibilidad que no esten actualizados

**5. Consideraciones sobre los datos sensibles**

* Tipod e de datos sensibles:
  - Información Personal Identificable :  Estat civil (marital), Ocupació (job).
  - Información Financera Sensible: saldo medio anual(balance), Tiene prestamo hipotecario  (housing), tiene prestamo personal (loan).
  - Datos comportamentales: duracion de la comunicación (duration), Numero de contactos (campaign), dias desde el ultimo contacto (pdays).

* Medidas de Protección:
  - Anonimización y Pseudonimización:
  Para datos como el estado civil y la ocupación, se puede aplicar pseudonimización, sustituyendo los valores por códigos. En el caso del saldo medio anual, se pueden aplicar técnicas de anonimización, agregando datos o utilizando intervalos en lugar de valores exactos.

  - Acceso Restringido:
  El acceso a los datos sensibles estará limitado al personal autorizado, con una necesidad justificada podrá acceder a esta información.

  - Cumplimiento de Regulaciones:
  Cumplimiento del  Reglamento General de Protección de Datos.